# Site settings
title: Ion
email: youknownothing.iter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  日拱一卒
  功不唐捐

twitter_username: jekyllrb
github_username:  jekyll

github_url: https://github.com/youknownothingg
baseurl: "/itstime" # the subpath of your site, e.g. /blog/
# repository: youknownothingg/youknownothingg.github.io
# url: https://youknownothingg.github.io

# Build settings
markdown: kramdown

theme: jekyll-theme-leap-day

# Navigation. main menu list
menus:

  -
    href:
    label: Home

  -

    href: cat/java
    label: Java

  -
    href: cat/springboot
    label: Spring Boot

  -
    href: cat/springcloud
    label: Spring Cloud
    subnav:

      -
        subHref: config
        subLabel: Spring Cloud Config

      -
        subHref: SpringCloudFeign
        subLabel: Spring Cloud Feign

  -
    href: cat/list
    label: Archieve

  -
    href: cat/casual
    label: Casual

  -
    href: cat/contact
    label: Contact

  -
    href: cat/about
    label: About
